# Default locale
locale: nl
# Cross-origin resource sharing related settings.
cors:
  # Allowed origins. Add one entry for each domain allowed to access the application.
  # Always include the protocol (http or https) and if not default for the
  # protocol, also the port number!
  origins:
    - http://localhost:9000/
    - http://localhost:9000

# Database settings
database:
  default:
    driver: pdo_mysql
    host:
    user:
    password:
    dbname:
  legacy_widgets:
    driver: pdo_mysql
    host:
    user:
    password:
    dbname:

# Mongodb settings
mongodb:
  default:
    host:
    port:
    user:
    password:
    dbname:

# UiTID related settings.
uitid:
  test:
    consumer:
      key:
      secret:
    base_url: https://acc2.uitid.be/uitid/rest/
  live:
    consumer:
      key:
      secret:
    base_url: https://www.uitid.be/uitid/rest/

# debug settings
debug: false

# Rabbit MQ settings
rabbitmq:
  host:
  port:
  user:
  password:
  vhost: /
  # Time in miliseconds before retrying a message
  failed_message_delay: 3600000 # 1 hour

# Insightly settings
insightly:
  host: https://api.insight.ly/v2.2
  api_key:
  project_config:

# Search API settings
search_api:
  test:
    base_url: https://search-acc.uitdatabank.be
    api_key:
  live:
    base_url: https://search.uitdatabank.be
    api_key:
  region-list: # location of the region export
  cache:
    enabled: true
    backend: filesystem # supported cache: filesystem or redis
    ttl: 3600

# Curatoren API settings
curatoren_api:
  test:
    base_url: https://curator-acc.uitdatabank.be/
  live:
    base_url: https://curator-acc.uitdatabank.be/
  cache:
    enabled: true
    backend: redis
    ttl: 3600

# Article Linker
articlelinker_api:
  test:
    base_url: https://curator-acc.uitdatabank.be/
  live:
    base_url: https://curator-acc.uitdatabank.be/
  cache:
    enabled: true
    backend: redis
    ttl: 3600

# Annotation settings
annotations:
  cache:
    enabled: true
    backend: filesystem # supported cache: filesystem or redis

# ODM and ORM settings
odm_orm:
  proxies_dir: /var/www/projectaanvraag-api/cache/proxies
  hydrator_dir: /var/www/projectaanvraag-api/cache/hydrators
  cache:
    enabled: true
    backend: filesystem

# Global cache settings
cache:
  redis:
    host:
    port: 6379

# Legacy widget host settings
legacy_host: http://tools.uitdatabank.be

# CSS stats settings
css_stats:
  timeout: 5
  connect_timeout: 1

# Google tag manager code
google_tag_manager:

# The default consumer group to use
default_consumer_group: 3

# App-URL
app_host: "http://projectaanvraag.uitdatabank.be"
social_host: "http://social.uit.be"
