services:
  php:
    build: docker/php
    hostname: 'projectaanvraag.local'
    container_name: php.projectaanvraag
    volumes:
      - .:/var/www/html:cached
    working_dir: /var/www/html
    ports:
      - '80:80'
    networks:
      projectaanvraag:
        aliases:
          - projectaanvraag
    healthcheck:
      test: curl http://127.0.0.1:80/
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: mysql.projectaanvraag
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - 'projectaanvraag-mysql:/var/lib/mysql'
    ports:
      - '${FORWARD_MYSQL_PORT:-3306}:3306'
    networks:
      projectaanvraag:
        aliases:
          - mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:alpine'
    container_name: redis.projectaanvraag
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'projectaanvraag-redis:/data'
    networks:
      - projectaanvraag
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      retries: 3
      timeout: 5s
  mongodb:
    image: 'mongo:3.6'
    container_name: mongodb.projectaanvraag
    ports:
      - '${FORWARD_MONGODB_PORT:-27017}:27017'
    volumes:
      - 'projectaanvraag-mongodb:/data/db'
    networks:
      - projectaanvraag
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
      retries: 3
      timeout: 5s
  rabbitmq:
    image: public.ecr.aws/y2o7k5u2/udb3/rabbitmq:latest
    hostname: 'rabbitdocker'
    volumes:
      - 'projectaanvraag-rabbitmq:/var/lib/rabbitmq/mnesia'
    container_name: rabbitmq.projectaanvraag
    ports:
      - '${FORWARD_RABBITMQ_PORT:-5672}:5672'
      - '${FORWARD_RABBITMQ_ADMIN_PORT:-15672}:15672'
    networks:
      - projectaanvraag
    healthcheck:
      test: [ 'CMD', 'rabbitmqctl', 'node_health_check' ]
      retries: 3
      timeout: 5s

networks:
  projectaanvraag:
    name: platform
    external: true

volumes:
  projectaanvraag-redis:
    driver: local
  projectaanvraag-mysql:
    driver: local
  projectaanvraag-mongodb:
    driver: local
  projectaanvraag-rabbitmq:
    driver: local
