subscribers:
    synchronous:
        CultuurNet\ProjectAanvraag\Widget\Event\SearchResultsQueryAlter:
            - widget_search_results_query_alter_listener
    asynchronous:
        CultuurNet\ProjectAanvraag\Project\Event\ProjectCreated:
            - leagcy_project_created_listener
            - project_created_listener
        CultuurNet\ProjectAanvraag\Project\Event\RequestedActivation:
            - legacy_requested_activation_listener
            - requested_activation_listener
        CultuurNet\ProjectAanvraag\Project\Event\ProjectDeleted:
            - legacy_project_deleted_listener
            - project_deleted_listener
        CultuurNet\ProjectAanvraag\Project\Event\ProjectBlocked:
            - legacy_project_blocked_listener
            - project_blocked_listener
        CultuurNet\ProjectAanvraag\Project\Event\ProjectActivated:
            - legacy_project_activated_listener
            - project_activated_listener
        CultuurNet\ProjectAanvraag\Core\Event\QueueConsumers:
            - queue_consumers_listener
        CultuurNet\ProjectAanvraag\Core\Event\SyncConsumer:
            - sync_consumer_listener
        CultuurNet\ProjectAanvraag\ArticleLinker\Event\ArticleLinkCreated:
            - articleLink_created_listener

listeners:
    articleLink_created_listener:
        class: \CultuurNet\ProjectAanvraag\ArticleLinker\EventListener\ArticleLinkCreatedEventListener
        arguments:
            - articlelinker_api
            - articlelinker_api_test
            - articlelinker_cache

    leagcy_project_created_listener:
        class: \CultuurNet\ProjectAanvraag\Project\EventListener\ProjectCreatedEventListener
        arguments:
            - legacy_insightly_client
            - insightly.project_config
            - orm.em
            - use_new_insightly_instance

    legacy_requested_activation_listener:
        class: \CultuurNet\ProjectAanvraag\Project\EventListener\RequestedActivationEventListener
        arguments:
            - legacy_insightly_client
            - insightly.project_config
            - use_new_insightly_instance

    legacy_project_activated_listener:
        class: \CultuurNet\ProjectAanvraag\Project\EventListener\ProjectActivatedEventListener
        arguments:
            - legacy_insightly_client
            - insightly.project_config
            - use_new_insightly_instance

    legacy_project_deleted_listener:
        class: \CultuurNet\ProjectAanvraag\Project\EventListener\ProjectDeletedEventListener
        arguments:
            - legacy_insightly_client
            - insightly.project_config
            - use_new_insightly_instance

    legacy_project_blocked_listener:
        class: \CultuurNet\ProjectAanvraag\Project\EventListener\ProjectBlockedEventListener
        arguments:
            - legacy_insightly_client
            - insightly.project_config
            - use_new_insightly_instance

    project_created_listener:
        class: \CultuurNet\ProjectAanvraag\Project\EventListener\Insightly\ProjectCreatedListener
        arguments:
            - insightly_client
            - orm.em
            - group_id_converter
            - use_new_insightly_instance
            - insightly_logger

    requested_activation_listener:
        class: \CultuurNet\ProjectAanvraag\Project\EventListener\Insightly\RequestedActivationListener
        arguments:
            - insightly_client
            - orm.em
            - group_id_converter
            - use_new_insightly_instance
            - insightly_logger

    project_activated_listener:
        class: \CultuurNet\ProjectAanvraag\Project\EventListener\Insightly\ProjectActivatedListener
        arguments:
            - insightly_client
            - orm.em
            - group_id_converter
            - use_new_insightly_instance
            - insightly_logger

    project_blocked_listener:
        class: \CultuurNet\ProjectAanvraag\Project\EventListener\Insightly\ProjectBlockedListener
        arguments:
            - insightly_client
            - orm.em
            - use_new_insightly_instance
            - insightly_logger

    project_deleted_listener:
        class: \CultuurNet\ProjectAanvraag\Project\EventListener\Insightly\ProjectDeletedListener
        arguments:
            - insightly_client
            - use_new_insightly_instance
            - insightly_logger

    queue_consumers_listener:
        class: \CultuurNet\ProjectAanvraag\Core\EventListener\QueueConsumersEventListener
        arguments:
            - culturefeed
            - culturefeed_test
            - event_bus

    sync_consumer_listener:
        class: \CultuurNet\ProjectAanvraag\Core\EventListener\SyncConsumerEventListener
        arguments:
            - project_repository
            - orm.em
            - insightly.project_config

    widget_search_results_query_alter_listener:
        class: \CultuurNet\ProjectAanvraag\Widget\EventListener\SearchResultsQueryAlterListener
        arguments:
            - request_stack

handlers:
    create_articleLink_handler:
        command: CultuurNet\ProjectAanvraag\ArticleLinker\Command\CreateArticleLink
        class: \CultuurNet\ProjectAanvraag\ArticleLinker\CommandHandler\CreateArticleLinkCommandHandler
        arguments:
            - event_bus

    create_project_handler:
        command: CultuurNet\ProjectAanvraag\Project\Command\CreateProject
        class: \CultuurNet\ProjectAanvraag\Project\CommandHandler\CreateProjectCommandHandler
        arguments:
            - event_bus
            - orm.em
            - culturefeed_test
            - culturefeed
            - uitid_user_session_data_complete
            - integration_types.storage
            - insightly_logger

    import_project_handler:
        command: CultuurNet\ProjectAanvraag\Project\Command\ImportProject
        class: \CultuurNet\ProjectAanvraag\Project\CommandHandler\ImportProjectCommandHandler
        arguments:
            - orm.em
            - insightly_logger

    activate_project_handler:
        command: CultuurNet\ProjectAanvraag\Project\Command\ActivateProject
        class: \CultuurNet\ProjectAanvraag\Project\CommandHandler\ActivateProjectCommandHandler
        arguments:
            - event_bus
            - orm.em
            - culturefeed
            - uitid_user_session_data_complete
            - integration_types.storage

    request_activation_handler:
        command: CultuurNet\ProjectAanvraag\Project\Command\RequestActivation
        class: \CultuurNet\ProjectAanvraag\Project\CommandHandler\RequestActivationCommandHandler
        arguments:
          - event_bus
          - orm.em

    delete_project_handler:
        command: CultuurNet\ProjectAanvraag\Project\Command\DeleteProject
        class: \CultuurNet\ProjectAanvraag\Project\CommandHandler\DeleteProjectCommandHandler
        arguments:
            - event_bus
            - orm.em
            - culturefeed
            - culturefeed_test
            - uitid_user_session_data_complete

    block_project_handler:
        command: CultuurNet\ProjectAanvraag\Project\Command\BlockProject
        class: \CultuurNet\ProjectAanvraag\Project\CommandHandler\BlockProjectCommandHandler
        arguments:
            - event_bus
            - orm.em
            - culturefeed
            - culturefeed_test
            - uitid_user_session_data_complete

    update_widget_page_handler:
          command: CultuurNet\ProjectAanvraag\Widget\Command\UpdateWidgetPage
          class: \CultuurNet\ProjectAanvraag\Widget\CommandHandler\UpdateWidgetPageCommandHandler
          arguments:
              - event_bus
              - mongodbodm.dm
              - uitid_user_session_data_complete

    create_widget_page_handler:
              command: CultuurNet\ProjectAanvraag\Widget\Command\CreateWidgetPage
              class: \CultuurNet\ProjectAanvraag\Widget\CommandHandler\CreateWidgetPageCommandHandler
              arguments:
                  - event_bus
                  - mongodbodm.dm
                  - uitid_user_session_data_complete
                  - uuid_generator

    publish_widget_page_handler:
          command: CultuurNet\ProjectAanvraag\Widget\Command\PublishWidgetPage
          class: \CultuurNet\ProjectAanvraag\Widget\CommandHandler\PublishWidgetPageCommandHandler
          arguments:
              - event_bus
              - mongodbodm.dm
              - widget_repository
              - uitid_user_session_data_complete

    revert_widget_page_handler:
          command: CultuurNet\ProjectAanvraag\Widget\Command\RevertWidgetPage
          class: \CultuurNet\ProjectAanvraag\Widget\CommandHandler\RevertWidgetPageCommandHandler
          arguments:
              - event_bus
              - widget_repository

    upgrade_widget_page_handler:
          command: CultuurNet\ProjectAanvraag\Widget\Command\UpgradeWidgetPage
          class: \CultuurNet\ProjectAanvraag\Widget\CommandHandler\UpgradeWidgetPageCommandHandler
          arguments:
              - event_bus
              - mongodbodm.dm
              - widget_repository
              - uitid_user_session_data_complete

    delete_widget_page_handler:
          command: CultuurNet\ProjectAanvraag\Widget\Command\DeleteWidgetPage
          class: \CultuurNet\ProjectAanvraag\Widget\CommandHandler\DeleteWidgetPageCommandHandler
          arguments:
              - event_bus
              - mongodbodm.dm
              - widget_repository
              - uitid_user_session_data_complete
