name: CI
on: push

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.4'
                  tools: pecl
                  extensions: mongodb
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
            - name: Run PHPUnit tests
              run: vendor/bin/phpunit
            - name: Coveralls
                uses: coverallsapp/github-action@master
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
